### ISSUE TITLE
how to change data files?

### ISSUE THREAD

**Issue by Janeyanhong** [kennethleungty/Llama-2-Open-Source-LLM-CPU-Inference#19]
first time I run the main program successfully, then I try to change the data file to be my own pdf file and ask related questions. 

But results always look like based on the original one.

results: 

D:\Llama-2-Open-Source-LLM-CPU-Inference>python main.py "how many years of experience in banking technology practitioners"

Answer: Mr. Woodward has 16 years of experience in banking and finance, including 9 years as a senior investment banker within J.P . Morgan’s international mergers and acquisitions team and 7 years in various senior finance roles at Ladbrokes.
==================================================

Source Document 1

Source Text: worked as a senior investment banker within J.P . Morgan’s international mergers and acquisitions teambetween 1999 and 2005. Prior to joining J.P . Morgan, Mr. Woodward worked for PricewaterhouseCoopersLLP in the Accounting and Tax advisory department between 1993 and 1999. He received a Bachelor ofScience degree in physics from Bristol University in 1993 and qualified for his Chartered Accountancyin 1996.
Document Name: data\manu-20f-2022-09-24.pdf
Page Number: 87

in fact the file is data/resume_cn1_en.pdf.

How can I handle this issue?

**Comment by Janeyanhong** [comment]
fixed it already, by running db_build.py to reload the changed file.

**Comment by kennethleungty** [comment]
Hi Jane, looks like you have indeed fixed it. Yeah rerunning db_build.py on the new documents is the way to go
